### ISSUE TITLE
org-todo-keywords-for-agenda reset after opening org-agenda

### ISSUE THREAD

**Issue by hxegon** [doomemacs/doomemacs#7106]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behavior

When setting `org-todo-keywords-for-agenda`, it shouldn't reset to the default value after the org agenda is opened.

### Current behavior

There are no errors or messages that look relevant to this issue.

From an elisp repl:
<img width="889" alt="Screen Shot 2023-02-23 at 2 12 26 PM" src="https://user-images.githubusercontent.com/1624302/221006878-222327da-b08d-47ad-9b31-8c3c1be430f2.png">

There's an issue that looks just like this (#2913) and the solution is to wrap the config in `after!`, but this is already in an `after!`.

I can also reproduce this from the elisp repl:
<img width="1076" alt="Screen Shot 2023-02-23 at 2 15 20 PM" src="https://user-images.githubusercontent.com/1624302/221007742-52859260-3831-4d67-896e-49461f9a3296.png">

### Steps to reproduce

1. Open emacs with the following in `config.el`:
```elisp
(after! org
  (setq org-agenda-files (directory-files-recursively "~/your/org/dir/" "\\.org$")
        org-todo-keywords '((sequence "TODO(t)" "DOING(D)" "BLOCKED(B)" "WAITING(w)" "CANCELED(c)" "|" "DONE(d)"))
        org-todo-keywords-for-agenda '((sequence "TODO" "DOING" "|" "DONE" "CANCELED"))))
```

2. Open an org file and check `org-todo-keywords-for-agenda`, it should be the value set above.
3. Open the org agenda (SPC o A a => `org-agenda')
4. check the value of `org-todo-keywords-for-agenda`, it's back to the default.

### System Information

https://pastebin.com/ef7aSKaK

**Comment by hxegon** [comment]
Closing this issue, not sure why but it started working.
