### ISSUE TITLE
Cannot archive TODO items anymore

### ISSUE THREAD

**Issue by tiagommmelo** [doomemacs/doomemacs#8177]
### I confirm that...

- [x] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [x] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [x] The issue can be reproduced on the **latest** available commit of Doom.

- [x] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

When I

```
M-x 'org-archive-subtree-default' (SPC m A)
```
on a TODO item, it should archive the item to an archive org file I set; I have the configuration line `#+ARCHIVE: %s_archive::` on top of my org file to achieve this.

### Current behavior

What happens instead is that the item is not archived and I get the error message in the mini buffer: **"Wrong type of argument: hash-table-p, nil"**

What I believe the problem is is that some item in my org file might have some wrong information that is preventing org-mode to work fine as it should; however, there are thousands of lines for me to search to begin with (and checking if this is really the issue). I'm coming back to Doom Emacs after a long time and I recall it happening to me once, and the issue was one TODO entry mal-formed; after manually deleting it, all worked back as normal. I might be mistaken, but it is a good lead. If there's a clever way for me to find this 'mal-formed' TODO entry, it might do the trick. Thanks in advance

### Steps to reproduce

1. Open doom emacs by running the command 'emacs' under windows subsystem for Linux (wsl)
2. Open an .org file with several TODO items
3. Place the cursor on an item that needs to be archived to the archive org file
4. Invoke the command 'SPC m A'

### System Information

https://pastebin.com/8nF6XWf9

**Comment by goodvibrations32** [comment]
Hey there, as i see your doom HEAD is pointing to 4790db6 and the current master is at 9c8cfaa so what i would do first regardless is `doom upgrade` to the latest. Many things are getting fixed really fast so a `doom sync -u` is at help some times especially with regressions.

### On the issue you are facing

I tried to reproduce this with no luck. A very nice resource is a debugger output which can give more info about the errors faces someone.

Henrik has a beautiful explanation and walk-through [here on discource](https://discourse.doomemacs.org/t/what-is-a-backtrace-how-to-produce-them/85) 

I hope this come handy to you and some backtrace is always helpful to others.

**Comment by tiagommmelo** [comment]
Hello and thanks for your guidance.
Here are the steps I made (steps 1 to 3 are not so important, step 4 is somewhat important step 5 onwards are important):

1. `doom upgrade` > it finished and upgraded fine
2. `doom upgrade` > I like to run this a second time just so it re-checks. This time, I received the message below with  options:
```
In repository "use-package", remote "origin" has URL
      "https://github.com/jwiegley/use-package.git"
    but recipe specifies a URL of
      "https://github.com/emacs-straight/use-package.git"

1) Abort
2) Rename remote "origin" to "origin-1", re-create "origin" with correct URL, and fetch
3) Rename remote "origin" manually, re-create it with correct URL, and fetch
4) Delete remote "origin", re-create it with correct URL, and fetch (Choose this if unsure)
5) Delete remote "origin", re-create it with manually set URL, and fetch
```
I chose option **4** and it worked with no errors
3. `doom sync -u` > also worked with no errors
4. Started Doom Emacs and tried to archive again with `SPC m A` and the error persists
5. Followed the walk-through (great resource by the way, thanks a lot for that one) and reproduced the debugger output; check below:

```
Debugger entered--Lisp error: (wrong-type-argument hash-table-p nil)
  puthash(#("c6c7461e-2ed2-4042-a44b-6354d759cca0" 0 36 (isearch-open-invisible org-fold-core--isearch-show isearch-open-invisible-temporary org-fold-core--isearch-show-temporary fontified t face org-property-value)) "/mnt/c/Users/tiago.melo/Dropbox/org/work.org_archi..." nil)
  org-id-add-location(#("c6c7461e-2ed2-4042-a44b-6354d759cca0" 0 36 (isearch-open-invisible org-fold-core--isearch-show isearch-open-invisible-temporary org-fold-core--isearch-show-temporary fontified t face org-property-value)) "/mnt/c/Users/tiago.melo/Dropbox/org/work.org_archi...")
  org-id-paste-tracker(#("** CANCELLED Change Alelo to \"Alimentação\" only [1..." 0 1 (face org-hide isearch-open-invisible-temporary org-fold-core--isearch-show-temporary isearch-open-invisible org-fold-core--isearch-show fontified t) 1 3 (face org-level-2 isearch-open-invisible-temporary org-fold-core--isearch-show-temporary isearch-open-invisible org-fold-core--isearch-show fontified t) 3 12 (face (org-done org-done org-level-2) isearch-open-invisible-temporary org-fold-core--isearch-show-temporary isearch-open-invisible org-fold-core--isearch-show fontified t) 12 13 (face org-level-2 isearch-open-invisible-temporary org-fold-core--isearch-show-temporary isearch-open-invisible org-fold-core--isearch-show fontified t) 13 48 (face (org-headline-done org-headline-done org-level-2) isearch-open-invisible-temporary org-fold-core--isearch-show-temporary isearch-open-invisible org-fold-core--isearch-show fontified t) 48 54 (face (org-checkbox-statistics-done org-headline-done org-checkbox-statistics-done org-headline-done org-level-2) isearch-open-invisible-temporary org-fold-core--isearch-show-temporary isearch-open-invisible org-fold-core--isearch-show fontified t) 54 55 (face org-level-2 isearch-open-invisible-temporary org-fold-core--isearch-show-temporary isearch-open-invisible org-fold-core--isearch-show fontified t) 55 65 (face org-special-keyword isearch-open-invisible-temporary org-fold-core--isearch-show-temporary isearch-open-invisible org-fold-core--isearch-show fontified t) 65 66 (isearch-open-invisible-temporary org-fold-core--isearch-show-temporary isearch-open-invisible org-fold-core--isearch-show fontified t) 66 81 (face (org-date org-date) keymap (keymap (follow-link . mouse-face) (mouse-3 . org-find-file-at-mouse) (mouse-2 . org-open-at-mouse)) mouse-face highlight isearch-open-invisible-temporary org-fold-core--isearch-show-temporary isearch-open-invisible org-fold-core--isearch-show fontified t) 81 82 (face (org-date org-date) rear-nonsticky (mouse-face highlight keymap invisible intangible help-echo org-linked-text htmlize-link) keymap (keymap (follow-link . mouse-face) (mouse-3 . org-find-file-at-mouse) (mouse-2 . org-open-at-mouse)) mouse-face highlight isearch-open-invisible-temporary org-fold-core--isearch-show-temporary isearch-open-invisible org-fold-core--isearch-show fontified t) 82 83 (isearch-open-invisible-temporary org-fold-core--isearch-show-temporary isearch-open-invisible org-fold-core--isearch-show fontified t) 83 95 (face org-drawer font-lock-fontified t isearch-open-invisible-temporary org-fold-core--isearch-show-temporary isearch-open-invisible org-fold-core--isearch-show fontified t) 95 96 (fontified t isearch-open-invisible-temporary org-fold-core--isearch-show-temporary isearch-open-invisible org-fold-core--isearch-show) 96 100 (face org-special-keyword fontified t isearch-open-invisible-temporary org-fold-core--isearch-show-temporary isearch-open-invisible org-fold-core--isearch-show) 100 107 (fontified t isearch-open-invisible-temporary org-fold-core--isearch-show-temporary isearch-open-invisible org-fold-core--isearch-show) ...))
  org-paste-subtree(1)
  org-archive-subtree(nil)
  funcall-interactively(org-archive-subtree nil)
  call-interactively(org-archive-subtree)
  org-archive-subtree-default()
  funcall-interactively(org-archive-subtree-default)
  call-interactively(org-archive-subtree-default nil nil)
  command-execute(org-archive-subtree-default)

```
6. I read the message and have a guess on where it 'breaks', but I have no clue of what might be wrong here.

One extra information that might be useful here: the issue does not happen for all tasks; some just get archived just fine. I tried to find a relation about what can be different on the few ones that can be archived and the great majority of the ones that I simply cannot do it (for example, tasks containing fewer drawers), but it seems that is not the issue anyway.

Any help is appreciated; thanks again and best regards, 
Tiago Melo

**Comment by goodvibrations32** [comment]
This suggests that the issue comes from the org-mode archiving thing. Can you make this happen with the `doom-sandbox` i.e. doom without your config but the modules loaded? 

If yes try `SPC m A` on vanilla emacs also. This will tell you if the error is from your config somehow and/or there are issues with the org-mode package. Use the `doom/sandbox` command either by `SPC m E` or `M-x doom/sandbox`.

You can find more for the sandbox [here](https://discourse.doomemacs.org/t/testing-elisp-packages-in-dooms-sandbox/74).

This is a really useful tool to help you narrow down bugs from your config. If the error persists even in vanilla emacs then you may have an **upstream** gem (issue) there. Either with org-mode or with emacs itself.. 

> One extra information that might be useful here: the issue does not happen for all tasks; some just get archived just fine. I tried to find a relation 

Try also to create a new fresh org file and use it as a test bench... If this archives without manual intervention (creating the archive file/folder/subtree) then could be with the org file itself..

The backtrace as you found out says that `pushash` does not return a proper hash table. 

### Just a tip...
The backtrace if has `...` somewhere this can be expanded (emacs renders this as a link) if you hit `RET` with the cursor on the dots..

You can also put some highlighting for languages on issues and comments on the platform... This helps in long backtraces.... just follow the three ` with the lang name (lisp in that case)

```lisp
(progn (message "Hi"))
```

**Comment by tiagommmelo** [comment]
Hello again. I realized that it does not happen in vanilla Emacs, but still happens in plain scratch Doom, so something must be wrong with some tasks only. What I did is that I deleted all tasks CANCELLED or DONE instead of archiving and created new ones. For the newly created tasks, the issues do not happen, so I assume that, as long as I only use new tasks, it'll not happen again.
I'll be using Doom Emacs actively the next week onwards, so if the error happens on a new created tasks I'll debug it and check what might be the cause; case it does not happen, I'll come back to this thread to mark this case as resolved. 
Thanks for now

**Comment by tiagommmelo** [comment]
Hello again.
After some time back to using doom emacs, not only was a relief (it feels so good to have evil keys in a text editor) but also, after deleting parts of text in tasks that were causing the issue in the first place, I no longer have issues with archiving. All works again.
It is a shame, though, that I did not go further in understanding exactly what is the real cause of the error itself, but I believe that at least I found a "workaround". Steps for the workaround (real simple) below:

1. When in need to archive a headline/task, do it as usual (`SPC m A`)
2. If the error occurs, either delete the headline and contents or, if you really want to archive it so you do not lose reference (in case you ever need to check that again), just create a new headline with the same contents and archive the new headline instead (and delete the problematic one afterwards)

And, with that, I'll mark this case solved. Thanks for the always excellent support :)

**Comment by hlissner** [comment]
Huh, very strange. I suspect something may have been wrong with your `org-id-locations-file` (lives in `"$EMACSDIR/.local/cache/.org-id-locations"` by default). Perhaps it was empty? Anyhow, how to tell after-the-fact, but glad to know it resolved itself.
